export const GET_FIGYRS = 'GET_FIGYRS';
export const CHANGE_EVENT_FISH = 'CHANGE_EVENT_FISH';

export const HELP_MOVE_PIECE_ON_OR_OFF = 'HELP_MOVE_PIECE_ON_OR_OFF';
export const USER_AUTH_LOGAUT = 'USER_AUTH_LOGAUT';
export const USER_AUTH_LOGIN = 'USER_AUTH_LOGIN';
export const ADD_OR_DELETE_TOKEN = 'ADD_OR_DELETE_TOKEN';